{% set name = "mlprodict" %}
{% set version = "0.5.1447" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlprodict-{{ version }}.tar.gz
  sha256: ffba0716a2e6bac60fa9ea83efb36cbb623334aca115bfd35fce29854dcd3f25

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - cython
    - jinja2
    - numpy
    - onnx >=1.7
    - pip
    - pybind11
    - python
    - scikit-learn >=0.23
  run:
    - cython
    - jinja2
    - numpy >=1.17
    - onnx >=1.7
    - pybind11
    - python
    - scipy >=1.0.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - mlprodict
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.xavierdupre.fr/app/mlprodict/helpsphinx/index.html
  summary: Python Runtime for ONNX models, other helpers to convert machine learned models in C++.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xhochy
