{% set name = "mlprodict" %}
{% set version = "0.8.1826" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlprodict-{{ version }}.tar.gz
  sha256: 00e4d21d6502b4e3642d825e275b947d162615cc7137fec68908c7c64404b503

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - numpy
    - pip
    - pybind11
    - pyquicksetup
    - python
  run:
    - cython
    - jinja2
    - onnx >=1.7.0
    - pybind11
    - python
    - scipy >=1.0.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - mlprodict
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.xavierdupre.fr/app/mlprodict/helpsphinx/index.html
  summary: Python Runtime for ONNX models, other helpers to convert machine learned models in C++.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xhochy
