{% set name = "mlprodict" %}
{% set version = "0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sdpython/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 81654c7533a647d39ab68f775a1d2516ab8b92a6853af4d6c9d620cb11730125

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - pyquicksetup
    - setuptools
    - cython
    - jinja2
    - numpy
    - onnx >=1.7
    - pip
    - pybind11
    - python
    - scikit-learn >=0.23
  run:
    - cython
    - jinja2
    - numpy >=1.17
    - onnx >=1.7
    - pybind11
    - python
    - scipy >=1.0.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - mlprodict
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.xavierdupre.fr/app/mlprodict/helpsphinx/index.html
  summary: Python Runtime for ONNX models, other helpers to convert machine learned models in C++.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xhochy
